### ISSUE TITLE
No SSR (Node.js) support

### ISSUE THREAD

**Issue by chris-vaimo** [adobe/magento-storefront-event-collector#135]
### Expected Behaviour
I am able import '@adobe/magento-storefront-event-collector' as described in the documentation on a headless environment (Node.js - Vue Storefront):

`import '@adobe/magento-storefront-event-collector';`

### Actual Behaviour
The entire PWA crashes with the following error:

```
ReferenceError: self is not defined
    at Object.<anonymous> (../node_modules/@adobe/magento-storefront-event-collector/dist/index.js:2:278)
```

#### Platform and Version
Vue Storefront V1 (Node Server Side Renderer)
"@adobe/magento-storefront-event-collector": "^1.1.12"

#### Logs taken while reproducing problem

Note: src/modules/adobe-sensei/index.ts:1:0 is where I am importing with:
`import '@adobe/magento-storefront-event-collector';`

```
ReferenceError: self is not defined
    at Object.<anonymous> (../node_modules/@adobe/magento-storefront-event-collector/dist/index.js:2:278)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at r (../node_modules/vue-server-renderer/build.dev.js:9315:16)
    at Object.@adobe/magento-storefront-event-collector (webpack:/external "@adobe/magento-storefront-event-collector":1:0)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Module../src/modules/adobe-sensei/index.ts (src/modules/adobe-sensei/index.ts:1:0)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Module../src/themes/rapala/config/modules.ts (src/themes/rapala/config/modules.ts:2:0)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Module../core/modules-entry.ts (server-bundle.js:6146:76)
    at __webpack_require__ (webpack/bootstrap:25:0)
```

### Additional Info

Vue Storefront supports Server Side Rendering, and in this case the import statements are done on both the server and then the client. None of the adobe modules seem to support Node.js gracefully.

The goal is not to have this working on Node.js, it is merely to have the modules not BREAK Node.js if they are imported within it.

**Comment by aniham** [comment]
tracked in [DINT-366](https://jira.corp.magento.com/browse/DINT-366)
